### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by tlkw79** [rrskybox/ImagePlanner#1]
Hi,
 
Having this issue when trying to install the latest version.

PLATFORM VERSION INFO
	Windows 			: 10.0.19042.0 (Win32NT)
	Common Language Runtime 	: 4.0.30319.42000
	System.Deployment.dll 		: 4.8.4270.0 built by: NET48REL1LAST_C
	clr.dll 			: 4.8.4341.0 built by: NET48REL1LAST_C
	dfdll.dll 			: 4.8.4270.0 built by: NET48REL1LAST_C
	dfshim.dll 			: 10.0.19041.1 (WinBuild.160101.0800)

SOURCES
	Deployment url			: file:///C:/Users/TomAstroTCU/Desktop/ImagePlanner-master/ImagePlanner/publish/ImagePlanner.application
	Application url			: file:///C:/Users/TomAstroTCU/Desktop/ImagePlanner-master/ImagePlanner/publish/Application%20Files/ImagePlanner_4_0_0_68/ImagePlanner.exe.manifest

IDENTITIES
	Deployment Identity		: ImagePlanner.application, Version=3.3.0.68, Culture=neutral, PublicKeyToken=0000000000000000, processorArchitecture=msil

APPLICATION SUMMARY
	* Installable application.

ERROR SUMMARY
	Below is a summary of the errors, details of these errors are listed later in the log.
	* Activation of C:\Users\TomAstroTCU\Desktop\ImagePlanner-master\ImagePlanner\publish\ImagePlanner.application resulted in exception. Following failure messages were detected:
		+ Application manifest has either a different computed hash than the one specified or no hash specified at all. 
		+ File, ImagePlanner.exe.manifest, has a different computed hash than specified in manifest.

COMPONENT STORE TRANSACTION FAILURE SUMMARY
	No transaction error was detected.

WARNINGS
	* The manifest for this application does not have a signature. Signature validation will be ignored.
	* The manifest for this application does not have a signature. Signature validation will be ignored.

OPERATION PROGRESS STATUS
	* [05-Apr-21 5:26:10 PM] : Activation of C:\Users\TomAstroTCU\Desktop\ImagePlanner-master\ImagePlanner\publish\ImagePlanner.application has started.
	* [05-Apr-21 5:26:10 PM] : Processing of deployment manifest has successfully completed.
	* [05-Apr-21 5:26:10 PM] : Installation of the application has started.

ERROR DETAILS
	Following errors were detected during this operation.
	* [05-Apr-21 5:26:10 PM] System.Deployment.Application.InvalidDeploymentException (HashValidation)
		- Application manifest has either a different computed hash than the one specified or no hash specified at all. 
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Application.DownloadManager.DownloadApplicationManifest(AssemblyManifest deploymentManifest, String targetDir, Uri deploymentUri, IDownloadNotification notification, DownloadOptions options, Uri& appSourceUri, String& appManifestPath)
			at System.Deployment.Application.ApplicationActivator.DownloadApplication(SubscriptionState subState, ActivationDescription actDesc, Int64 transactionId, TempDirectory& downloadTemp)
			at System.Deployment.Application.ApplicationActivator.InstallApplication(SubscriptionState& subState, ActivationDescription actDesc)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl, Uri& deploymentUri)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
--- End of stack trace from previous location where exception was thrown ---
			at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
			at System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)
		--- Inner Exception ---
		System.Deployment.Application.InvalidDeploymentException (HashValidation)
		- File, ImagePlanner.exe.manifest, has a different computed hash than specified in manifest.
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Application.ComponentVerifier.VerifyFileHash(String filePath, Hash hash)
			at System.Deployment.Application.ComponentVerifier.VerifyFileHash(String filePath, HashCollection hashCollection)
			at System.Deployment.Application.DownloadManager.DownloadApplicationManifest(AssemblyManifest deploymentManifest, String targetDir, Uri deploymentUri, IDownloadNotification notification, DownloadOptions options, Uri& appSourceUri, String& appManifestPath)

COMPONENT STORE TRANSACTION DETAILS
	No transaction information is available.

**Comment by rrskybox** [comment]
I screwed up the zip file during that last upload.  It should be fixed now.  Just download, extract and open setup.exe.

 

*	Rick

 

From: Tommy ***@***.***> 
Sent: Sunday, April 4, 2021 11:28 PM
To: rrskybox/ImagePlanner ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [rrskybox/ImagePlanner] installation issue (#1)

 

Hi,

Having this issue when trying to install the latest version.

PLATFORM VERSION INFO
Windows : 10.0.19042.0 (Win32NT)
Common Language Runtime : 4.0.30319.42000
System.Deployment.dll : 4.8.4270.0 built by: NET48REL1LAST_C
clr.dll : 4.8.4341.0 built by: NET48REL1LAST_C
dfdll.dll : 4.8.4270.0 built by: NET48REL1LAST_C
dfshim.dll : 10.0.19041.1 (WinBuild.160101.0800)

SOURCES
Deployment url : file:///C:/Users/TomAstroTCU/Desktop/ImagePlanner-master/ImagePlanner/publish/ImagePlanner.application
Application url : file:///C:/Users/TomAstroTCU/Desktop/ImagePlanner-master/ImagePlanner/publish/Application%20Files/ImagePlanner_4_0_0_68/ImagePlanner.exe.manifest

IDENTITIES
Deployment Identity : ImagePlanner.application, Version=3.3.0.68, Culture=neutral, PublicKeyToken=0000000000000000, processorArchitecture=msil

APPLICATION SUMMARY
* Installable application.

ERROR SUMMARY
Below is a summary of the errors, details of these errors are listed later in the log.
* Activation of C:\Users\TomAstroTCU\Desktop\ImagePlanner-master\ImagePlanner\publish\ImagePlanner.application resulted in exception. Following failure messages were detected:
+ Application manifest has either a different computed hash than the one specified or no hash specified at all.
+ File, ImagePlanner.exe.manifest, has a different computed hash than specified in manifest.

COMPONENT STORE TRANSACTION FAILURE SUMMARY
No transaction error was detected.

WARNINGS
* The manifest for this application does not have a signature. Signature validation will be ignored.
* The manifest for this application does not have a signature. Signature validation will be ignored.

OPERATION PROGRESS STATUS
* [05-Apr-21 5:26:10 PM] : Activation of C:\Users\TomAstroTCU\Desktop\ImagePlanner-master\ImagePlanner\publish\ImagePlanner.application has started.
* [05-Apr-21 5:26:10 PM] : Processing of deployment manifest has successfully completed.
* [05-Apr-21 5:26:10 PM] : Installation of the application has started.

ERROR DETAILS
Following errors were detected during this operation.
* [05-Apr-21 5:26:10 PM] System.Deployment.Application.InvalidDeploymentException (HashValidation)
- Application manifest has either a different computed hash than the one specified or no hash specified at all.
- Source: System.Deployment
- Stack trace:
at System.Deployment.Application.DownloadManager.DownloadApplicationManifest(AssemblyManifest deploymentManifest, String targetDir, Uri deploymentUri, IDownloadNotification notification, DownloadOptions options, Uri& appSourceUri, String& appManifestPath)
at System.Deployment.Application.ApplicationActivator.DownloadApplication(SubscriptionState subState, ActivationDescription actDesc, Int64 transactionId, TempDirectory& downloadTemp)
at System.Deployment.Application.ApplicationActivator.InstallApplication(SubscriptionState& subState, ActivationDescription actDesc)
at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl, Uri& deploymentUri)
at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
at System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)
--- Inner Exception ---
System.Deployment.Application.InvalidDeploymentException (HashValidation)
- File, ImagePlanner.exe.manifest, has a different computed hash than specified in manifest.
- Source: System.Deployment
- Stack trace:
at System.Deployment.Application.ComponentVerifier.VerifyFileHash(String filePath, Hash hash)
at System.Deployment.Application.ComponentVerifier.VerifyFileHash(String filePath, HashCollection hashCollection)
at System.Deployment.Application.DownloadManager.DownloadApplicationManifest(AssemblyManifest deploymentManifest, String targetDir, Uri deploymentUri, IDownloadNotification notification, DownloadOptions options, Uri& appSourceUri, String& appManifestPath)

COMPONENT STORE TRANSACTION DETAILS
No transaction information is available.

**Comment by tlkw79** [comment]
Still haven't fix yet. :(

**Comment by rrskybox** [comment]
My apologies.  I mixed up repositories.  It should be fixed now.
If you are using TSX x32, then download ImagePlanner32.zip, extract to a folder on your system, and launch setup.
If you are using TSX x64, then download ImagePlanner64.zip. extract to a folder on your system, and launch setup.

Let me know if it works for you this time.

**Comment by backroadrider** [comment]
Hi Rick,

Just an FYI to let you know that I had no trouble installing ImagePlanner64 on my system after downloading from your repository this morning; and it is up and running and working as expected w/ TSX x64.

ImagePlanner is a fantastic tool that I use regularly so: 1) thank you for creating it in the first place; and 2) thank you for porting it to TSX x64!  I managed to get all of my observatory hardware and automation software to play nicely with TSX x64 so now I can put TSX x32 to bed, hopefully for good.

Thanks again for this most useful application,

Steve

**Comment by rrskybox** [comment]
Hey Steve,

 

Glad to hear it.  Always nice to know.  

 

- Rick
