### ISSUE TITLE
Image Planner Error When using LDN targets

### ISSUE THREAD

**Issue by astromiester1** [rrskybox/ImagePlanner#12]
I noticed LDN targets produce an error when typing in the image planner interface.  SKYX shows the LDN target after you type in image planner and hit return but image planner gags.

Examples tried... LDN 1251, LDN 1235... However, LDN 1622 works fine.

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Xml.XmlException: The '^' character, hexadecimal value 0x5E, cannot be included in a name.
   at System.Xml.XmlConvert.VerifyNCName(String name, ExceptionType exceptionType)
   at System.Xml.Linq.XName..ctor(XNamespace ns, String localName)
   at System.Xml.Linq.XNamespace.GetName(String localName)
   at System.Xml.Linq.XName.Get(String expandedName)
   at System.Xml.Linq.XName.op_Implicit(String expandedName)
   at ImagePlanner.FormImagePlanner.FillInTargetDetails(String tName)
   at ImagePlanner.FormImagePlanner.WriteTitle(String tgtName, String tYear)
   at ImagePlanner.FormImagePlanner.RegenerateForms()
   at ImagePlanner.FormImagePlanner.TargetNameBox_TextChanged(Object sender, KeyPressEventArgs e)
   at System.Windows.Forms.Control.OnKeyPress(KeyPressEventArgs e)
   at System.Windows.Forms.Control.ProcessKeyEventArgs(Message& m)
   at System.Windows.Forms.Control.ProcessKeyMessage(Message& m)
   at System.Windows.Forms.Control.WmKeyChar(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.TextBoxBase.WndProc(Message& m)
   at System.Windows.Forms.TextBox.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by rrskybox** [comment]
TSX is returning an unexpected character from the LDN catalog in a property name ("~size...").  I culled it and things seem better now.  Let me know if you find any collateral damage from my "fix".

**Comment by astromiester1** [comment]
I installed the 64bit version... Nope, the issue is still present when trying LDN 1235 or LDN 1251.. Here is the error below...

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Xml.XmlException: The '^' character, hexadecimal value 0x5E, cannot be included in a name.
   at System.Xml.XmlConvert.VerifyNCName(String name, ExceptionType exceptionType)
   at System.Xml.Linq.XName..ctor(XNamespace ns, String localName)
   at System.Xml.Linq.XNamespace.GetName(String localName)
   at System.Xml.Linq.XName.Get(String expandedName)
   at System.Xml.Linq.XName.op_Implicit(String expandedName)
   at ImagePlanner.FormImagePlanner.FillInTargetDetails(String tName)
   at ImagePlanner.FormImagePlanner.WriteTitle(String tgtName, String tYear)
   at ImagePlanner.FormImagePlanner.RegenerateForms()
   at ImagePlanner.FormImagePlanner.TargetNameBox_TextChanged(Object sender, KeyPressEventArgs e)
   at System.Windows.Forms.Control.OnKeyPress(KeyPressEventArgs e)
   at System.Windows.Forms.Control.ProcessKeyEventArgs(Message& m)
   at System.Windows.Forms.Control.ProcessKeyMessage(Message& m)
   at System.Windows.Forms.Control.WmKeyChar(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.TextBoxBase.WndProc(Message& m)
   at System.Windows.Forms.TextBox.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by rrskybox** [comment]
My fault -- I was testing on an old catalog database.  Updated and found another illegal XML character in the TSX property name fields.  Build 100 should be good to go.

**Comment by astromiester1** [comment]
Do you know when build 100 will be available?

**Comment by astromiester1** [comment]
I only see build 99.. Can you upload build 100 please where you say the latest fix is?

Thanks
Dale

**Comment by rrskybox** [comment]
Yep.  Done.

**Comment by astromiester1** [comment]
Version 100 still does not work... Tested with LDN 1235

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Xml.XmlException: The '^' character, hexadecimal value 0x5E, cannot be included in a name.
   at System.Xml.XmlConvert.VerifyNCName(String name, ExceptionType exceptionType)
   at System.Xml.Linq.XName..ctor(XNamespace ns, String localName)
   at System.Xml.Linq.XNamespace.GetName(String localName)
   at System.Xml.Linq.XName.Get(String expandedName)
   at System.Xml.Linq.XName.op_Implicit(String expandedName)
   at ImagePlanner.FormImagePlanner.FillInTargetDetails(String tName)
   at ImagePlanner.FormImagePlanner.WriteTitle(String tgtName, String tYear)
   at ImagePlanner.FormImagePlanner.RegenerateForms()
   at ImagePlanner.FormImagePlanner.TargetNameBox_TextChanged(Object sender, KeyPressEventArgs e)
   at System.Windows.Forms.Control.OnKeyPress(KeyPressEventArgs e)
   at System.Windows.Forms.Control.ProcessKeyEventArgs(Message& m)
   at System.Windows.Forms.Control.ProcessKeyMessage(Message& m)
   at System.Windows.Forms.Control.WmKeyChar(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.TextBoxBase.WndProc(Message& m)
   at System.Windows.Forms.TextBox.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by rrskybox** [comment]
Drat, another swing and a miss.  Try 101.

**Comment by astromiester1** [comment]
Success... Thank you Rick....Your the best....Dale...
