### ISSUE TITLE
Found AstroMath.dll had to compile at 64bit // runtime error now

### ISSUE THREAD

**Issue by astromiester1** [rrskybox/ImagePlanner#3]
(https://user-images.githubusercontent.com/14363854/218269556-2b0e751c-6e7d-421f-9471-165b136bb353.jpg)

Got this runtime error now....

System.Runtime.InteropServices.COMException
  HResult=0x800702E4
  Message=Retrieving the COM class factory for component with CLSID {0E0015B2-8EB6-4CA1-8A19-1A8BA6540C64} failed due to the following error: 800702e4 The requested operation requires elevation. (Exception from HRESULT: 0x800702E4).
  Source=mscorlib
  StackTrace:
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at ImagePlanner.FormImagePlanner..ctor() in C:\Users\Owner\Downloads\ImagePlanner-master\ImagePlanner\FormImagePlanner.cs:line 102
   at ImagePlanner.Program.Main() in C:\Users\Owner\Downloads\ImagePlanner-master\ImagePlanner\Program.cs:line 19

**Comment by rrskybox** [comment]
See comment about running TSX in administrator mode one time and one time only after a TSX update,  as described in issue #2.

**Comment by rrskybox** [comment]
Closed -- see Issue #2.
